class TripSearch():
    origin=""
    destination=""
    departureDate=""
    returnDate=""
    adults=""
    children=""
    travelClass=""
    nonStop=""
    currency=""
    max=""
    includeAirlines=""
    targetDepartureFlightNumber=""
    targetArrivalFlightNumber=""
